# EU Tenders - Sample Notebook

## Explore data

In [1]:

import pandas as pd        

# Read csv file
dataframe = pd.read_csv("./data/02-silver/eu-tenders-public-transport/eu-tenders-public-transport-DEG.csv")

In [2]:

# Display 5 first rows
dataframe.head()

    notice-type  ...                                         notice-url
0  can-standard  ...  https://ted.europa.eu/de/notice/-/detail/21221...
1  can-standard  ...  https://ted.europa.eu/de/notice/-/detail/19226...
2  can-standard  ...  https://ted.europa.eu/de/notice/-/detail/17880...
3      pin-tran  ...  https://ted.europa.eu/de/notice/-/detail/89539...
4   cn-standard  ...  https://ted.europa.eu/de/notice/-/detail/86386...

[5 rows x 25 columns]

In [3]:

# Display dataframe info
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 25 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   notice-type                          406 non-null    str
 1   place-of-performance                 406 non-null    str
 2   procedure-type                       406 non-null    str
 3   publication-date                     406 non-null    str
 4   publication-number                   406 non-null    str
 5   buyer-name                           406 non-null    str
 6   title-proc                           308 non-null    str
 7   additional-info-proc                 93 non-null     str
 8   document-url-lot                     121 non-null    str
 9   option-description-lot               54 non-null     str
 10  description-lot                      88 non-null     str
 11  description-proc                     278 non-null    str
 12  contract-duration-start-date-lot     175 non-null    str
 13  contract-duration-end-date-lot       146 non-null    str
 14  winner-name                          102 non-null    str
 15  main-classification-proc             308 non-null    float64
 16  direct-award-justification-proc      13 non-null     str
 17  selection-criterion-description-lot  46 non-null     str
 18  organisation-contact-point-buyer     200 non-null    str
 19  organisation-tel-buyer               282 non-null    str
 20  organisation-email-buyer             308 non-null    str
 21  renewal-maximum-lot                  47 non-null     str
 22  total-value                          125 non-null    float64
 23  award-criterion-type-lot             78 non-null     str
 24  notice-url                           406 non-null    str
dtypes: float64(2), str(23)
memory usage: 2.0 MB

In [4]:

# Describe dataframe
dataframe.describe()

       main-classification-proc   total-value
count              3.080000e+02  1.250000e+02
mean               6.021194e+07  4.720211e+06
std                5.771769e+06  2.232874e+07
min                1.421240e+07  0.000000e+00
25%                6.010000e+07  1.000000e+00
50%                6.013000e+07  4.200000e+05
75%                6.020000e+07  2.084034e+06
max                9.091100e+07  1.764706e+08