# EU Tenders - Sample Notebook

## Explore data

In [1]:

import pandas as pd        

# Read csv file
dataframe = pd.read_csv("./data/01-bronze/eu-tenders-public-transport/eu-tenders-public-transport-DEG.csv")

In [2]:

# Display 5 first rows
dataframe.head()

    notice-type  ...                           award-criterion-type-lot
0  can-standard  ...                                          ['price']
1  can-standard  ...  ['price', 'price', 'price', 'price', 'price', ...
2  can-standard  ...  ['price', 'price', 'price', 'price', 'price', ...
3      pin-tran  ...                                                NaN
4   cn-standard  ...  ['price', 'price', 'price', 'price', 'price', ...

[5 rows x 24 columns]

In [3]:

# Display dataframe info
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 24 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   notice-type                          46 non-null     str
 1   place-of-performance                 46 non-null     str
 2   procedure-type                       46 non-null     str
 3   publication-date                     46 non-null     str
 4   publication-number                   46 non-null     str
 5   buyer-name                           46 non-null     str
 6   title-proc                           45 non-null     str
 7   additional-info-proc                 32 non-null     str
 8   document-url-lot                     37 non-null     str
 9   option-description-lot               7 non-null      str
 10  description-lot                      45 non-null     str
 11  description-proc                     45 non-null     str
 12  contract-duration-start-date-lot     44 non-null     str
 13  contract-duration-end-date-lot       41 non-null     str
 14  winner-name                          1 non-null      str
 15  main-classification-proc             45 non-null     str
 16  direct-award-justification-proc      3 non-null      str
 17  selection-criterion-description-lot  33 non-null     str
 18  organisation-contact-point-buyer     24 non-null     str
 19  organisation-tel-buyer               45 non-null     str
 20  organisation-email-buyer             45 non-null     str
 21  renewal-maximum-lot                  6 non-null      str
 22  total-value                          8 non-null      float64
 23  award-criterion-type-lot             32 non-null     str
dtypes: float64(1), str(23)
memory usage: 1.5 MB

In [4]:

# Describe dataframe
dataframe.describe()

        total-value
count  8.000000e+00
mean   4.547929e+07
std    8.088572e+07
min    1.000000e-02
25%    3.258701e+05
50%    1.440117e+06
75%    4.969147e+07
max    1.764706e+08